### ISSUE TITLE
【Q】对ffmpeg生成的波形图分析实现时间轴自动对齐的可行性探讨

### ISSUE THREAD

**Issue by onlunar** [1c7/Subtitle-Timeline-Editor#3]
>（( ゜ -゜)つロ 乾杯~罕见地发现了字幕组+开发同行大佬，种草！）

> 一直想用`electron`+`ffmpeg`做一款时间轴相关的高效工具，奈何`electron`只写过demo，`ffmpeg`只用过命令行，触及到很多知识盲区，就很难啃下来。。。

> 目前在用人人译视界（QT+Webview），界面、操作对新用户没什么友好度，但是熟练之后还是行业标杆软件，之前想逆向几个小工具，也无疾而终了。。。

> 现在有大佬开Repo了，可以站在大佬的肩上尝试贡献一点开发力量了~

如题，目前做单英字cc，可能大部分为以下三种场景之一
+ 手工听写+手工打轴
+ 手工敲字+手工打轴
+ 网易见外TTS生成字幕+手工调轴

本Issue想提出的问题是针对字幕初步轴好或在校对阶段调轴时，能否对ffmpeg生成波形图进行人声波峰识别、切分，将其与字幕的粗轴进行细匹配，自动调整字幕出入时间

> 本地语音识别不确定只需要人声算法还是说要内置tensorflow模型，后者感觉有点难啃kkkkk

> 最后，UI点个赞！也还是electron比较适合做现代化UI（比如重构的迅雷）

**Comment by 1c7** [comment]
可以加我微信 agoodob

**Comment by 1c7** [comment]
我倾向于一步步来，先把最基础的，完全没有任何智能的这种手工打轴体验弄好。
后续再来整这个。等前一步做好了，按理来说后一步会更好做一些

**Comment by 1c7** [comment]
我是 ML/AI/tensorflow 菜鸡

**Comment by 1c7** [comment]
有个软件叫  Descript，你可以参考一下，做 podcast 的一个软件
